namespace Everlong.DI.Generators.Constants;

internal static class Conventions
{
  internal const string GeneratorSuffix = ".g.cs";
  internal const string AutoGeneratedHeader = "// <auto-generated/>\n#pragma warning disable\n#nullable enable\n\n";

  internal const string InjectedFieldPrefix = "__injected_";
}
