namespace Everlong.DI.Generators.Constants;

internal static class Conventions
{
  internal const string GeneratorSuffix = ".g.cs";
  internal const string AutoGeneratedHeader = "// <auto-generated/>\n#pragma warning disable\n#nullable enable\n\n";

  // Δ (U+0394) is the generator-reserved prefix: user partial code can neither collide
  // with nor accidentally reference members starting with it (typing Δ requires copying
  // the generated name), while ordinary "__" conventions stay free for user code.
  internal const string ReservedPrefix = "Δ";

  internal const string InjectedFieldPrefix = ReservedPrefix + "injected_";

  // Local used to buffer a member's resolution before the level-wide commit (two-phase
  // injection: all-or-nothing per level). Distinct from InjectedFieldPrefix so it can never
  // collide with a generated backing field.
  internal const string InjectedLocalPrefix = "__inject_value_";
}
